Revert "Remove unused imports from read"
This reverts commit db9c4d8571a172e5102aca7e0edde9c7cc4010ef.

I got a build failure:

> ReferenceError: jsx is not defined