Supply an Attribute for the GSI sort key
gh-278

I got an error like:

Error: Resolution error: Supplied properties not correct for
"CfnTableProps"
  attributeDefinitions: element 3: supplied properties not correct for
"AttributeDefinitionProperty"
    attributeName: required but missing
    attributeType: required but missing
  globalSecondaryIndexes: element 0: supplied properties not correct for
"GlobalSecondaryIndexProperty"
    keySchema: element 1: supplied properties not correct for
"KeySchemaProperty"
      attributeName: required but missing.

because sortKey of a GSI has to be an Attribute.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.GlobalSecondaryIndexProps.html#properties