npm i after a cdk module was missing
https://github.com/douglasnaphas/madliberation/issues/254

I got this error:

```
$ cdk synth > dev-template-01.yml
Cannot find module '@aws-cdk/aws-apigateway'
Require stack:
- /Users/dougnaphas/repos/madliberation/lib/madliberation-stack.js
- /Users/dougnaphas/repos/madliberation/bin/madliberation.ts
Subprocess exited with error 1
```

and running npm i, resulting in the present changes to
package-lock.json, fixed it.