Install infra before running roll call
My last build failed with errors complaining about "console" and
"process" being missing.

TSError: ⨯ Unable to compile TypeScript:
scripts/idp-app-secret-roll-call.ts(9,3): error TS2584: Cannot find name
'console'. Do you need to change your target library? Try changing the
'lib' compiler option to include 'dom'.
scripts/idp-app-secret-roll-call.ts(9,29): error TS2580: Cannot find
name 'process'. Do you need to install type definitions for node? Try
`npm i --save-dev @types/node`.