Log ssmResponse.data, a param's unexpectedly set
gh-281

The last build failed one the ue1 deploy with:

Run npx cdk bootstrap
us-east-1
error: sesEmailVerificationFromAddress expected, but not set
to fix this, set this param:
DouglasnaphasMadliberation281-ses-sesEmailVerificationFromAddress
or leave it unset, and unset this one:
DouglasnaphasMadliberation281-ses-sesEmailVerificationFromRegion
Subprocess exited with error

This doesn't make sense, because neither of those params are set for
us-east-1.